# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/0dbae39f-939d-42eb-916e-5372ba2c203f";
    fsType = "btrfs";
    options = ["subvol=root"];
  };

  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/a8a2540a-60c9-4fee-b4ff-7740d27822cc";

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/0dbae39f-939d-42eb-916e-5372ba2c203f";
    fsType = "btrfs";
    options = ["subvol=persist"];
  };

  fileSystems."/etc" = {
    device = "/persist/persist/etc";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/0dbae39f-939d-42eb-916e-5372ba2c203f";
    fsType = "btrfs";
    options = ["subvol=nix"];
  };

  fileSystems."/var/lib" = {
    device = "/dev/disk/by-uuid/0dbae39f-939d-42eb-916e-5372ba2c203f";
    fsType = "btrfs";
    options = ["subvol=lib"];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/0dbae39f-939d-42eb-916e-5372ba2c203f";
    fsType = "btrfs";
    options = ["subvol=log"];
  };

  fileSystems."/etc/NetworkManager/system-connections" = {
    device = "/var/log/persist/etc/NetworkManager/system-connections";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/0dbae39f-939d-42eb-916e-5372ba2c203f";
    fsType = "btrfs";
    options = ["subvol=home"];
  };

  fileSystems."/persist/swap" = {
    device = "/dev/disk/by-uuid/0dbae39f-939d-42eb-916e-5372ba2c203f";
    fsType = "btrfs";
    options = ["subvol=persist/swap"];
  };

  fileSystems."/root" = {
    device = "/persist/swap/persist/root";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/srv" = {
    device = "/persist/swap/persist/srv";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/var/lib/bluetooth" = {
    device = "/persist/swap/persist/var/lib/bluetooth";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/var/spool" = {
    device = "/persist/swap/persist/var/spool";
    fsType = "none";
    options = ["bind"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/BCD8-8C51";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
